openapi: 3.0.0
info:
  title: User API
  description: API to manage users
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Health check point for server
      response:
        '200':
          description: Server health route
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#components/schemas/Health'
        

  /users:
    get:
      summary: Get a list of users
      description: Retrieves a list of users, optionally filtered by name.
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Name filter for user lookup.
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    Health:
      type: object
      properties:
        msg:
          type: string
      required:
        - msg
    User:
      type: object
      properties:
        filterUser:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                description: The unique identifier of the user.
              name:
                type: string
                description: The name of the user.
            required:
            - id
            - name