kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-week29-scaling
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3007
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3008
  - containerPort: 10250
    hostPort: 10550
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3009
  - containerPort: 10250
    hostPort: 10551
