apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-backend
  namespace: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-dep
  template:
    metadata:
      labels:
        app: nginx-dep
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80