apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  database_url: "bXlzcWw6Ly9lY29tLWRiOjMzMDYvZWNvbW1lcmNlZnNkZg=="
  .env: "REFUQUJBU0VfVVJMPSJwb3N0Z3JlczovL3VzZXI6cGFzc3dvcmRAbG9jYWxob3N0OjU0MzIvdGVzdGRiIgpDQUNIRV9TSVpFPTEwMApQQVlNRU5UX0dBVEVXQVlfVVJMPSJodHRwczovL3BheW1lbnQtZ2F0ZXdheS5jb20iCk1BWF9DQVJUX0lURU1TPTEwClNFU1NJT05fVElNRU9VVD0xODAw"
  