apiVersion: v1
kind: Secret
metadata:
  name: express-app-secret
data:
  # database_url: bXlzcWw6Ly9lY29tLWRiOjMzMDYvc2VjcmV0U2hvcA==  # Base64 of mysql://ecom-db:3306/secretShop
  .env: REFUQUJBU0VfVVJMPSJteXNxbDovL2Vjb20tZGI6MzMwNi9zZWNyZXRTaG9wIgpDQUNIRV9TSVpFPTEwMDAKUEFZTUVOVF9HQVRFV0FZX1VSTD0iaHR0cHM6Ly9wYXltZW50LWdhdGV3YXkuZXhhbXBsZS5jb20iCk1BWF9DQVJUX0lURU1TPTUwClNFU1NJT05fVElNRU9VVD0zNjAw
  