apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
spec:
  containers:
    - name: nginx-2
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata: 
  name: postgres
spec:
  containers:
    - name: postgres
      image: "postgres:16.2"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: admin123
