kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ingres
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3007
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3008
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 3009